#pragma once

#include "framework.h"
#include "RenderContext.h"
#include "RenderPipeline.h"

class RenderObject;
class RenderPipeline;
class RenderWindow;

typedef enum ImageLayoutType {
    IMAGE_LAYOUT_UNDEFINED = 0,
    IMAGE_LAYOUT_GENERAL = 1,
    IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL = 2,
    IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL = 3,
    IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL = 4,
    IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL = 5,
    IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL = 6,
    IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL = 7,
    IMAGE_LAYOUT_PREINITIALIZED = 8,
    IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL = 1000117000,
    IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL = 1000117001,
    IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL = 1000241000,
    IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL = 1000241001,
    IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL = 1000241002,
    IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL = 1000241003,
    IMAGE_LAYOUT_READ_ONLY_OPTIMAL = 1000314000,
    IMAGE_LAYOUT_ATTACHMENT_OPTIMAL = 1000314001,
    IMAGE_LAYOUT_RENDERING_LOCAL_READ = 1000232000,
    IMAGE_LAYOUT_PRESENT_SRC_KHR = 1000001002,
    IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR = 1000024000,
    IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR = 1000024001,
    IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR = 1000024002,
    IMAGE_LAYOUT_SHARED_PRESENT_KHR = 1000111000,
    IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT = 1000218000,
    IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR = 1000164003,
    IMAGE_LAYOUT_VIDEO_ENCODE_DST_KHR = 1000299000,
    IMAGE_LAYOUT_VIDEO_ENCODE_SRC_KHR = 1000299001,
    IMAGE_LAYOUT_VIDEO_ENCODE_DPB_KHR = 1000299002,
    IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT = 1000339000,
    IMAGE_LAYOUT_VIDEO_ENCODE_QUANTIZATION_MAP_KHR = 1000553000,
    IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL,
    IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL,
    IMAGE_LAYOUT_SHADING_RATE_OPTIMAL_NV = VK_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR,
    IMAGE_LAYOUT_RENDERING_LOCAL_READ_KHR = VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ,
    IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL,
    IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL_KHR = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL,
    IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL,
    IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL_KHR = VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL,
    IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR = VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL,
    IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL,
    IMAGE_LAYOUT_MAX_ENUM = 0x7FFFFFFF
} ImageLayoutType;

class RenderTarget
{
public:
    
    RenderTarget(VkFormat format, int width, int height, ImageLayoutType type = ImageLayoutType::IMAGE_LAYOUT_PRESENT_SRC_KHR);
    ~RenderTarget();

    void beginDraw();
    void drawObject(RenderPipeline& pipeline, RenderObject& object);
    void endDraw();
    
    VkRenderPass& getRenderPass();
    void setRenderContext(RenderContext* renderContext);
    RenderContext& getRenderContext();
    
    VkImageView& getImage(glm::uint32 frame);
    std::vector<VkImageView> const& getImages();

    VkImageView createImageView(VkImage image, VkFormat format);

private:

    VkClearValue m_clearColor = { {{0.1f, 0.1f, 0.1f, 1.0f}} };
    UniformBufferObject m_globalBuffer;
    UboDataDynamic m_perObjectBuffer;
    int currentObject = 0;

    RenderContext*              m_renderContext;  
            
    VkFormat                    m_format;
    VkImageLayout               m_imageType;
    VkExtent2D                  m_extent{};
    VkOffset2D                  m_offset{};
    
    VkRenderPass                m_renderPass;
    
    std::vector<VkImage>        m_images;
    std::vector<VkImageView>    m_imageViews;
    std::vector<VkFramebuffer>  m_framebuffers;
    std::vector<VkDeviceMemory> m_imagesMemory;

    void createRenderPass();

    void createImages();
    void createImageViews();
    void createFramebuffers();

};
